services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_api:local
    ports: 
      - "5001:5000"
    volumes:
      - ./:/app    
    environment:
      - ENV=development
      - DOCKER_HOST_PORT=5001
    command: ["python", "main.py"] 
